name = "AKSMP + Les3Soleils"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df503dbfcd1662649996afc663f939923ae889b69dfab35a734a6abd78e3dc28"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
