name = "AKSMP + Les3Soleils"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a04f910fa42a510eeed5c2a6f93de9b14a7b278ae2a0749db08bf293868c493f"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
